# Generated by Django 3.0.10 on 2021-02-09 09:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20210209_0849'),
        ('program', '0006_auto_20201210_1114'),
    ]

    operations = [
        migrations.AddField(
            model_name='slot',
            name='students',
            field=models.ManyToManyField(through='program.StudentSlotAssociation', to='users.Student'),
        ),
        migrations.AddField(
            model_name='studentslotassociation',
            name='priority',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='studentslotassociation',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.Student'),
        ),
    ]
