# Generated by Django 3.0.10 on 2021-02-09 09:47

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20210209_0849'),
        ('program', '0007_auto_20210209_0946'),
    ]

    operations = [
        migrations.CreateModel(
            name='MentorSlotAssociation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, null=True)),
                ('deleted', models.BooleanField(default=False)),
                ('external_id', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ('priority', models.IntegerField(default=0)),
                ('mentor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.Mentor')),
                ('slot', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='program.Slot')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='slot',
            name='mentors',
            field=models.ManyToManyField(through='program.MentorSlotAssociation', to='users.Mentor'),
        ),
    ]
