# Generated by Django 3.0.10 on 2021-02-18 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0009_auto_20210209_1308'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentorslotassociation',
            name='is_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
