# Generated by Django 3.0.10 on 2021-04-11 15:39

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20210411_1539'),
        ('program', '0010_mentorslotassociation_is_confirmed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='program',
            old_name='calendar_id',
            new_name='googe_calendar_id',
        ),
        migrations.RenameField(
            model_name='slot',
            old_name='hangouts_link',
            new_name='meeting_link',
        ),
        migrations.RemoveField(
            model_name='program',
            name='announcements_group',
        ),
        migrations.RemoveField(
            model_name='program',
            name='collaboration_group',
        ),
        migrations.RemoveField(
            model_name='program',
            name='default_language',
        ),
        migrations.AddField(
            model_name='computer',
            name='computer_issues',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='computer',
            name='computer_model',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='computer',
            name='harward_specifications',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='computer',
            name='has_headphones',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='computer',
            name='headphone_specs',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='computer',
            name='manufactured_date',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='computer',
            name='mp_start_date',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='computer',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='computer',
            name='software_Notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='computer',
            name='wifi_connectivityInfo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='program',
            name='chief_contact',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='program',
            name='facebook_group',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='program',
            name='googleClassroom_url',
            field=models.URLField(blank=True, help_text='url link', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='program',
            name='googleDrive_url',
            field=models.URLField(blank=True, help_text='url link', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='program',
            name='latitude',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='program',
            name='longitude',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='program',
            name='mentor_announcements',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='program',
            name='mentor_collaboration',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='program',
            name='ministry_education_contact',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='program',
            name='notes',
            field=models.TextField(blank=True, help_text='comments, suggestions, notes, events, open-house dates, mentor program break dates, internet connectivity, power avalibility, state of infrastructure, etc', null=True),
        ),
        migrations.AddField(
            model_name='program',
            name='notion_url',
            field=models.URLField(blank=True, help_text='url link', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='program',
            name='parents_group',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='program',
            name='program_googlePhotos',
            field=models.URLField(blank=True, help_text='url link to google drive program photo folder', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='program',
            name='program_inception_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='program',
            name='program_renewal_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='program',
            name='required_languages',
            field=models.CharField(choices=[('ENGLISH', 'ENGLISH'), ('SPANISH', 'SPANISH'), ('VIETNAMSE', 'VIETNAMESE'), ('TAGALOG', 'TAGALOG'), ('HINDI', 'HINDI')], default=None, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='program',
            name='secondary_languages',
            field=models.CharField(choices=[('ENGLISH', 'ENGLISH'), ('SPANISH', 'SPANISH'), ('VIETNAMSE', 'VIETNAMESE'), ('TAGALOG', 'TAGALOG'), ('HINDI', 'HINDI')], default=None, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='program',
            name='students_group',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='program',
            name='village_chief',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='program',
            name='workplace_resources',
            field=models.URLField(blank=True, help_text='url link', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='monthly_fundingDollars',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='school_bio',
            field=models.TextField(blank=True, help_text='mission, values, vision, pitch', null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='school_goals',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='school_infrastructureNotes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='school_needs',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='school_successes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='studentNum',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='teacherNum',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='vbb_rating',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='slot',
            name='slot_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='program',
            name='program_director',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.ProgramDirector'),
        ),
        migrations.AlterField(
            model_name='program',
            name='village_info_link',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='slot',
            name='language',
            field=models.CharField(choices=[('ENGLISH', 'ENGLISH'), ('SPANISH', 'SPANISH'), ('VIETNAMSE', 'VIETNAMESE'), ('TAGALOG', 'TAGALOG'), ('HINDI', 'HINDI')], max_length=254),
        ),
        migrations.CreateModel(
            name='TeachersProgramAssociation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, null=True)),
                ('deleted', models.BooleanField(default=False)),
                ('external_id', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ('priority', models.IntegerField(default=0)),
                ('is_confirmed', models.BooleanField(default=False)),
                ('program', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teacher_program', to='program.Program')),
                ('teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='program_teacher', to='users.Teacher')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ManagersProgramAssociation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, null=True)),
                ('deleted', models.BooleanField(default=False)),
                ('external_id', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ('priority', models.IntegerField(default=0)),
                ('is_confirmed', models.BooleanField(default=False)),
                ('manager', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='program_manager', to='users.ProgramManager')),
                ('program', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manager_program', to='program.Program')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HeadmastersProgramAssociation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, null=True)),
                ('deleted', models.BooleanField(default=False)),
                ('external_id', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ('priority', models.IntegerField(default=0)),
                ('is_confirmed', models.BooleanField(default=False)),
                ('headmaster', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='program_headmaster', to='users.HeadMaster')),
                ('program', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='headmaster_program', to='program.Program')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='program',
            name='headmasters',
            field=models.ManyToManyField(through='program.HeadmastersProgramAssociation', to='users.HeadMaster'),
        ),
        migrations.AddField(
            model_name='program',
            name='managers',
            field=models.ManyToManyField(through='program.ManagersProgramAssociation', to='users.ProgramManager'),
        ),
        migrations.AddField(
            model_name='program',
            name='teachers',
            field=models.ManyToManyField(through='program.TeachersProgramAssociation', to='users.Teacher'),
        ),
    ]
