version: 2.1


jobs:
  Test-Build:
    docker:
      - image: cimg/python:3.8.5
        environment:
          PGHOST: 127.0.0.1
          PGUSER: vbb
          TEST_DATABASE_URL: "postgres://vbb@localhost/vbb"
      - image: circleci/redis:5.0.6-buster
      - image: circleci/postgres:latest
        environment:
          POSTGRES_USER: vbb
          POSTGRES_DB: vbb
          POSTGRES_HOST_AUTH_METHOD: trust
    steps:
      - checkout
      - restore_cache:
          key: v2-{{ .Branch }}-{{ checksum "requirements.txt" }}
      - run:
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      - save_cache:
          key: v2-{{ .Branch }}-{{ checksum "requirements.txt" }}
          paths:
            - venv
      - run:
          name: Running tests
          no_output_timeout: 30m
          command: |
            . venv/bin/activate && pytest

workflows:
  Run-Tests:
    jobs:
      - Test-Build
