# Generated by Django 3.0.10 on 2021-02-15 15:09

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20210209_0849'),
        ('session', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MentorSessionAssociation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, null=True)),
                ('deleted', models.BooleanField(default=False)),
                ('external_id', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ('attended', models.BooleanField(default=False)),
                ('mentor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mentor_session', to='users.Mentor')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='session',
            name='derived_from',
        ),
        migrations.RemoveField(
            model_name='session',
            name='is_mentor_confirmed',
        ),
        migrations.RemoveField(
            model_name='studentsessionassociation',
            name='is_absent',
        ),
        migrations.RemoveField(
            model_name='studentsessionassociation',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='studentsessionassociation',
            name='wont_attend',
        ),
        migrations.AddField(
            model_name='studentsessionassociation',
            name='attended',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='studentsessionassociation',
            name='session',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='session_student', to='session.Session'),
        ),
        migrations.AlterField(
            model_name='studentsessionassociation',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_session', to='users.Student'),
        ),
        migrations.DeleteModel(
            name='SessionRule',
        ),
        migrations.AddField(
            model_name='mentorsessionassociation',
            name='session',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='session_mentor', to='session.Session'),
        ),
    ]
