# Generated by Django 3.0.10 on 2021-02-18 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20210209_0849'),
        ('program', '0010_mentorslotassociation_is_confirmed'),
        ('session', '0002_auto_20210215_1509'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='mentors',
            field=models.ManyToManyField(through='session.MentorSessionAssociation', to='users.Mentor'),
        ),
        migrations.AddField(
            model_name='session',
            name='slot',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='program.Slot'),
        ),
        migrations.AddField(
            model_name='session',
            name='students',
            field=models.ManyToManyField(through='session.StudentSessionAssociation', to='users.Student'),
        ),
    ]
