# Generated by Django 3.0.10 on 2021-04-11 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0011_auto_20210411_1539'),
        ('session', '0003_auto_20210218_1512'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='notes',
        ),
        migrations.AddField(
            model_name='mentorsessionassociation',
            name='delay_notes',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mentorsessionassociation',
            name='feedback',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='mentorsessionassociation',
            name='issues',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='mentorsessionassociation',
            name='mentoring_notes',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='mentorsessionassociation',
            name='warnings',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='agenda',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='computer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='program.Computer'),
        ),
        migrations.AddField(
            model_name='session',
            name='headmaster_notes',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='infrastructure_notes',
            field=models.TextField(blank=True, default=None, help_text='Power, wifi, audio quality?', null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='isHappening',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='session',
            name='mentee_notes',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='mentorAdvisor_notes',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='otherNotes',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='parent_notes',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='student_notes',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='teacher_notes',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='studentsessionassociation',
            name='delay_notes',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='studentsessionassociation',
            name='feedback',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='studentsessionassociation',
            name='issues',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='studentsessionassociation',
            name='mentoring_notes',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='studentsessionassociation',
            name='warnings',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
