# Generated by Django 3.0.10 on 2021-03-18 20:42

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20210209_0849'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, null=True)),
                ('deleted', models.BooleanField(default=False)),
                ('external_id', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ('personal_email', models.EmailField(max_length=254, null=True, unique=True, verbose_name='Personal Email')),
                ('subscriber_type', models.CharField(blank=True, max_length=70, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
