# Generated by Django 3.0.10 on 2021-04-11 15:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20210209_0849'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mentor',
            name='address',
        ),
        migrations.RemoveField(
            model_name='mentor',
            name='charged',
        ),
        migrations.RemoveField(
            model_name='mentor',
            name='desired_involvement',
        ),
        migrations.RemoveField(
            model_name='user',
            name='initials',
        ),
        migrations.RemoveField(
            model_name='user',
            name='occupation',
        ),
        migrations.RemoveField(
            model_name='user',
            name='referral_source',
        ),
        migrations.RemoveField(
            model_name='user',
            name='vbb_chapter',
        ),
        migrations.AddField(
            model_name='mentor',
            name='additional_involvement',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='mentor',
            name='application_submitted',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='mentor',
            name='attended_training',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='mentor',
            name='completed_trainingModules',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='mentor',
            name='follow_up',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='mentor',
            name='headmaster_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mentor',
            name='initials',
            field=models.CharField(max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='mentor',
            name='isIncomplete',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='mentor',
            name='isInterested',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='mentor',
            name='isStaff',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='mentor',
            name='isinCoporateEmployeeProgram',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='mentor',
            name='leadmentor_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mentor',
            name='legal_notes_bymentor',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mentor',
            name='legal_notes_byreviewer',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mentor',
            name='mentorAdvisor_notes',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='mentor',
            name='mentor_application_video_link',
            field=models.URLField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='mentor',
            name='metHeadmaster',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='mentor',
            name='metMentorAdvisor',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='mentor',
            name='nextLeadMentor_meetingInfo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mentor',
            name='nextLeadMentor_meeting_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mentor',
            name='occupation',
            field=models.CharField(blank=True, max_length=70, null=True, verbose_name='Occupation'),
        ),
        migrations.AddField(
            model_name='mentor',
            name='onetime_donated',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='mentor',
            name='recurring_donation',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='mentor',
            name='referral_source',
            field=models.TextField(blank=True, max_length=200, null=True, verbose_name='Refferal'),
        ),
        migrations.AddField(
            model_name='mentor',
            name='terms_agreement',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='mentor',
            name='trainingNotes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mentor',
            name='trainingScheduled',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='mentor',
            name='vbb_chapter',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='VBB Chapter'),
        ),
        migrations.AddField(
            model_name='mentor',
            name='vetted',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='avaibility_times',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='country',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE'), ('OTHER', 'OTHER')], default=None, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='secondary_language',
            field=models.CharField(choices=[('ENGLISH', 'ENGLISH'), ('SPANISH', 'SPANISH'), ('VIETNAMSE', 'VIETNAMESE'), ('TAGALOG', 'TAGALOG'), ('HINDI', 'HINDI')], default=None, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='state',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='user_bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='user_renewal_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='primary_language',
            field=models.CharField(choices=[('ENGLISH', 'ENGLISH'), ('SPANISH', 'SPANISH'), ('VIETNAMSE', 'VIETNAMESE'), ('TAGALOG', 'TAGALOG'), ('HINDI', 'HINDI')], default=None, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.IntegerField(choices=[(100, 'STUDENT'), (150, 'PARENT'), (200, 'MENTOR'), (300, 'TEACHER'), (400, 'HEADMASTER'), (500, 'PROGRAM_DIRECTOR'), (600, 'PROGRAM_MANAGER'), (700, 'EXECUTIVE')], default=200),
        ),
        migrations.AlterField(
            model_name='userquestionarequestions',
            name='user_type',
            field=models.IntegerField(blank=True, choices=[(100, 'STUDENT'), (150, 'PARENT'), (200, 'MENTOR'), (300, 'TEACHER'), (400, 'HEADMASTER'), (500, 'PROGRAM_DIRECTOR'), (600, 'PROGRAM_MANAGER'), (700, 'EXECUTIVE')], default=None, null=True),
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, null=True)),
                ('deleted', models.BooleanField(default=False)),
                ('external_id', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProgramManager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, null=True)),
                ('deleted', models.BooleanField(default=False)),
                ('external_id', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProgramDirector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, null=True)),
                ('deleted', models.BooleanField(default=False)),
                ('external_id', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.HeadMaster')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, null=True)),
                ('deleted', models.BooleanField(default=False)),
                ('external_id', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Executive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, null=True)),
                ('deleted', models.BooleanField(default=False)),
                ('external_id', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='headmaster',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.Teacher'),
        ),
    ]
