# Generated by Django 3.0.10 on 2021-03-21 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20210320_1804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newslettersubscriber',
            name='subscriber_type',
            field=models.CharField(choices=[('REGISTRATION', 'REGISTRATION'), ('VBB_NEWSLETTER', 'VBB_NEWSLETTER')], default='VBB_NEWSLETTER', max_length=254),
        ),
    ]
