# Generated by Django 3.0.10 on 2021-04-11 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20210411_1539'),
        ('users', '0014_auto_20210410_1229'),
    ]

    operations = [
    ]
